const projects = [
  {
    name: "Memor.i.eye",
    summary:
      "A dashboard where u can see all the images taken by the eye-tracking glasses from AdHawk",
    aim: "To build something that could capture the best moments of a persons day and show them in a dashboard where the images are sorted and can be searched by date, time and description that was generated by a image to text AI",
    impact:
      "This was my team's final submission for HTN(Hack the North). In my eyes I believe we won. Nonetheless, it was a unique and an inspiring experience where I got to work with and against the best developers from all around the planet.",
    learned:
      "How to interact with a flask backend (that accesses the database and uses the AdHawk API to capture the images and store them in the database) with the NextJS frontend",
    image: "memor-i-eye",
    video: "",
    github: "https://github.com/NilsIrl/eyes",
    website: "https://memori-eye.vercel.app/",
    languages: ["TypeScript React", "Python"],
    date: "2022-09",
    //     type: "Project Type",
    technologies: [
      "AdHawk API",
      "openCV",
      "google cloud vision",
      "cohere.ai",
      "CockroachDB",
      "Flask",
      "Next.js",
      "Chakra-UI",
      "tailwindcss",
      "framer-motion",
    ],
    wakatime:
      '<a href="https://wakatime.com/badge/user/33addb7e-f5e6-470b-a55b-0a8babc62ebb/project/17605001-4c93-43d8-b471-8ae3284bbe76"><img src="https://wakatime.com/badge/user/33addb7e-f5e6-470b-a55b-0a8babc62ebb/project/17605001-4c93-43d8-b471-8ae3284bbe76.svg?style=flat-square" alt="wakatime"></a>',
  },
  {
    name: "Open Seat Notifier",
    summary: "Get notified when a new research participation study is up",
    aim: "Automates the process of constantly checking if there are research participation opportunities which is one of the requirements for 3 intro Psychology courses in University of Calgary. Instead, you get an email notification when there is a new research participation opportunity.",
    impact:
      "Saved my classmates and I some time and inspired one of my friends to start learning web scraping.",
    learned:
      "Learned how to setup and use an SQL database on a server and how to encrypt and decrypt the data. In addition, this project counter-intuitively taught me the limitless possibilities of APIs since they're basically an 'official' way of web scraping (GETing data off the web)",
    image: "open-seat-notifier",
    video: "Hs70CLeK1OI",
    github: "https://github.com/psycho-baller/open-seat-notifier",
    website: "https://open-seat-notifier.vercel.app/",
    languages: ["TypeScript React", "Python"],
    date: "2021-11",
    //     type: "Project Type",
    technologies: [
      "PostgreSQL",
      "Prisma",
      "Next.js",
      "Selenium",
      "Selenium Webdriver",
      "Chakra-UI",
      "tailwindcss",
      "framer-motion",
      "EmailJS",
    ],
    wakatime:
      '<a href="https://wakatime.com/badge/user/33addb7e-f5e6-470b-a55b-0a8babc62ebb/project/790ea500-6623-4ca0-8d24-29c31f9bb2c5"><img src="https://wakatime.com/badge/user/33addb7e-f5e6-470b-a55b-0a8babc62ebb/project/790ea500-6623-4ca0-8d24-29c31f9bb2c5.svg?style=flat-square" alt="wakatime"></a>',
  },
  {
    name: "Psycho Driver",
    summary: "Race against a car taught how to drive using neural networks",
    aim: "Wanted to understand the 'back-end' of AI and specifically neural networks. So I decided to build a self-driving car that learned how to drive using neural networks without any libraries.",
    impact:
      "An entertaining way to learn about neural networks, where you can see the car learn how to drive in real-time with the neural networks visualized in learning mode.",
    learned:
      "Followed the process of Software Development Life Cycle (SDLC) to build the app from its small simple features to a full-on complex app made of several simple functionalities. Also, I used Svelte for the first time so I learned the basics of SvelteKit too",
    image: "psycho-driver",
    video: "",
    github: "https://github.com/psycho-baller/self-driving-car",
    website: "https://psycho-driver.vercel.app/",
    languages: ["TypeScript"],
    date: "2022-08",
    //     type: "Project Type",
    technologies: ["SvelteKit", "SvelteUI"],
    wakatime:
      '<a href="https://wakatime.com/badge/user/33addb7e-f5e6-470b-a55b-0a8babc62ebb/project/9cdb42ee-e237-443b-9352-f7a5c4e0677d"><img src="https://wakatime.com/badge/user/33addb7e-f5e6-470b-a55b-0a8babc62ebb/project/9cdb42ee-e237-443b-9352-f7a5c4e0677d.svg" alt="wakatime"></a>',
  },
];

export default projects;